import { createFileRoute } from '@tanstack/react-router';

export const Route = createFileRoute('/legal')({
  component: LegalPage,
});

function LegalPage() {
  return (
    <div className="mx-auto max-w-3xl py-12 px-4 max-sm:px-2">
      <h1 className="text-2xl font-bold mb-2 text-center">Legal & Policies</h1>
      <p className="text-sm text-muted-foreground mb-6 text-center">Last Updated: February 20, 2026</p>

      <div className="flex flex-col gap-6">
        {/* Terms of Service */}
        <section className="rounded-xl border border-border bg-card p-6">
          <h2 className="text-base font-semibold mb-4">1. Terms of Service</h2>
          <p className="text-base text-foreground/60 mb-4">
            Welcome to Boosted Flow. By using our service, you agree to these terms.
          </p>

          <div className="flex flex-col gap-4">
            <div>
              <h3 className="font-semibold mb-2">1.1 Use of the Service</h3>
              <p className="text-foreground/60">
                Boosted Flow provides a time tracking and productivity tool. You must create an account
                to use the service and are responsible for keeping your login credentials secure.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-2">1.2 Acceptable Use</h3>
              <p className="text-foreground/60">
                You agree not to misuse our service. This includes not attempting to disrupt our
                systems, reverse-engineer the app, or use the service for any illegal activities.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-2">1.3 User Data</h3>
              <p className="text-foreground/60">
                You retain all rights to the data you create (such as your activities, time entries,
                and tracking history). We only access this data to provide and improve the service.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-2">1.4 Service Availability</h3>
              <p className="text-foreground/60">
                We strive to keep the service running smoothly, but we provide it "as is." We do not
                guarantee that the service will be uninterrupted or error-free.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-2">1.5 Account Termination</h3>
              <p className="text-foreground/60">
                You can cancel your account at any time. We reserve the right to suspend or terminate
                accounts that violate these terms.
              </p>
            </div>

            <p className="text-foreground/60">
              Contact: For any questions about these terms, contact us at{' '}
              <a href="mailto:support@boosted-flow.com" className="underline hover:text-foreground transition-colors duration-150">
                support@boosted-flow.com
              </a>
              .
            </p>
          </div>
        </section>

        {/* Privacy Policy */}
        <section className="rounded-xl border border-border bg-card p-6">
          <h2 className="text-base font-semibold mb-4">2. Privacy Policy</h2>

          <div className="flex flex-col gap-4">
            <div>
              <h3 className="font-semibold mb-2">2.1 What We Collect</h3>
              <p className="text-foreground/60 mb-3">
                To provide our service, we collect the following:
              </p>
              <ul className="flex flex-col gap-2">
                <li className="text-foreground/60">
                  <span className="font-medium text-foreground">Account Information:</span> Email
                  address and basic profile information used for authentication.
                </li>
                <li className="text-foreground/60">
                  <span className="font-medium text-foreground">App Data:</span> Your tracked time
                  entries, custom activities, pomodoro settings, and analytics data generated by your
                  use of the app.
                </li>
                <li className="text-foreground/60">
                  <span className="font-medium text-foreground">Device & Usage Data:</span> Basic
                  technical information (like browser type and general usage patterns) to help us
                  debug issues and improve the app.
                </li>
              </ul>
            </div>

            <div>
              <h3 className="font-semibold mb-2">2.2 How We Use Your Data</h3>
              <p className="text-foreground/60">
                We use your data solely to operate the app, sync your tracking sessions, compute your
                analytics, and provide customer support.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-2">2.3 Data Sharing</h3>
              <p className="text-foreground/60">
                We do not sell your personal data. We only share data with trusted third-party
                services necessary to run our app (such as cloud hosting and payment processors like
                Paddle).
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-2">2.4 Account Deletion</h3>
              <p className="text-foreground/60">
                You have the right to request the complete deletion of your account and all associated
                personal data. To have your account deleted, please email us at{' '}
                <a href="mailto:support@boosted-flow.com" className="underline hover:text-foreground transition-colors duration-150">
                  support@boosted-flow.com
                </a>{' '}
                from the email address associated with your account. We will process your deletion
                request manually within 30 days.
              </p>
            </div>
          </div>
        </section>

        {/* Refund Policy */}
        <section className="rounded-xl border border-border bg-card p-6">
          <h2 className="text-base font-semibold mb-4">3. Refund Policy</h2>
          <p className="text-base text-foreground/60 mb-4">
            Our order process is conducted by our online reseller & Merchant of Record, Paddle.com, who handles all sales-related inquiries.
          </p>

          <div className="flex flex-col gap-4">
            <div>
              <h3 className="font-semibold mb-2">3.1 Subscription Cancellations</h3>
              <p className="text-foreground/60">
                You can cancel your subscription at any time. Once canceled, you will not be charged
                again, and you will retain access to your premium features until the end of your
                current billing cycle.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-2">3.2 14-Day Money-Back Guarantee</h3>
              <p className="text-foreground/60">
                If you are not satisfied with your purchase, we offer a full refund within 14 days of your purchase date. 
                This applies to all purchases, including subscription renewals.
              </p>
            </div>

            <div>
              <h3 className="font-semibold mb-2">3.3 Requesting a Refund</h3>
              <p className="text-foreground/60">
                To request a refund within the 14-day window, please contact us at{' '}
                <a href="mailto:support@boosted-flow.com" className="underline hover:text-foreground transition-colors duration-150">
                  support@boosted-flow.com
                </a>{' '}
                with your account email and receipt. Refunds will be processed back to your original
                payment method via our payment processor, Paddle, in accordance with{' '}
                <a 
                  href="https://www.paddle.com/legal/invoiced-consumer-terms" 
                  target="_blank" 
                  rel="noreferrer" 
                  className="underline hover:text-foreground transition-colors duration-150"
                >
                  Paddle's Consumer Terms
                </a>.
              </p>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}
